### ISSUE TITLE
black-nb==0.3.0 is incompatible with black==20.8b1 (latest)

### ISSUE THREAD

**Issue by dkmiller** [tomcatling/black-nb#55]
Title should be pretty self-descriptive. I'm using the Anaconda installation of Python 3.7.6 in a Windows machine. If I run:

```bash
pip install black==20.8b1 black-nb==0.3.0
```

and then run `black-nb .` in a directory (can be empty), I get this error:

```
Traceback (most recent call last):
  File "c:\users\danmill\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\danmill\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\users\danmill\Miniconda3\Scripts\black-nb.exe\__main__.py", line 7, in <module>
  File "c:\users\danmill\miniconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\danmill\miniconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\danmill\miniconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\danmill\miniconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\danmill\miniconda3\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\danmill\miniconda3\lib\site-packages\black_nb\cli.py", line 171, in cli
    black.gen_python_files_in_dir(
AttributeError: module 'black' has no attribute 'gen_python_files_in_dir'
```

**Comment by Xloka** [comment]
should we go back to previous version ??

**Comment by dkmiller** [comment]
@Xloka reverting to the previous version of `black` fixed things. Ideally, there would be a fix to `black-nb` to make it compatible with the latest version of `black`.
