### ISSUE TITLE
Compatibility issue with latest Black release (22.1.0)

### ISSUE THREAD

**Issue by tlinhart** [tomcatling/black-nb#71]
When using v0.6 with the latest Black version (22.1.0), I get this error:

```
$ black-nb --clear-output .
Traceback (most recent call last):
  File "/home/user/tmp/project/venv/bin/black-nb", line 8, in <module>
    sys.exit(cli())
  File "/home/user/tmp/project/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/tmp/project/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/user/tmp/project/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/tmp/project/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/tmp/project/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/tmp/project/venv/lib/python3.8/site-packages/black_nb/cli.py", line 194, in cli
    sources = black.get_sources(
  File "src/black/__init__.py", line 626, in get_sources
TypeError: 'NoneType' object is not subscriptable
```

**Comment by zapaishchykova** [comment]
+1
