### ISSUE TITLE
Incompatible with current release of black

### ISSUE THREAD

**Issue by gmattar** [tomcatling/black-nb#75]
```
Traceback (most recent call last):
  File "./env/bin/black-nb", line 8, in <module>
    sys.exit(cli())
  File "./env/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "./env/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "./env/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "./env/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "./env/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./env/lib/python3.9/site-packages/black_nb/cli.py", line 195, in cli
    sources = black.get_sources(
TypeError: get_sources() missing required keyword-only argument 'root'
```

  black-nb 0.7
  black 23.11.0

**Comment by Avs163** [comment]
One solution is to create a virtual env with python 3.7 version, activate the env, and then do pip install black-nb and then run the command. It would work.
